### ISSUE TITLE
Add Apple Silicon Support to GUIX cross compliations

### ISSUE THREAD

**Issue by gto90** [DigiByte-Core/digibyte#111]
**Is your feature request related to a problem? Please describe.**
At the present time, the GUIX cross compilation capability added by this [PR](https://github.com/DigiByte-Core/digibyte/pull/108) does not support Apple Silicon and will fail with indeterminant errors.

**Describe the solution you'd like**
Resolve GUIX errors when compiling for Apple Silicon.

**Comment by saltedlolly** [comment]
Has there been any progress on this? 

It would be really helpful to be able to compile DigiByte Core on modern Macs.

**Comment by ycagel** [comment]
https://github.com/DigiByte-Core/digibyte/pull/194 has been merged solving this issue.

**Comment by saltedlolly** [comment]
I'm not 100% sure this has been solved, or at least it has not been tested yet. (Compiling on a Silicon Mac with GUIX)

It might be okay but we should probably keep this open till we are certain.

**Comment by gto90** [comment]
> I'm not 100% sure this has been solved, or at least it has not been tested yet. (Compiling on a Silicon Mac with GUIX)
> 
> It might be okay but we should probably keep this open till we are certain.

If you can compile, build, and make check, this issue can be closed, in my opinion. If there are application-level issues, such as hanging or slow startup, we should track those separately in discrete issues. This issue deals explicitly with the errors that were happening when trying to compile with M1 Macs, and I believe that issue is now resolved.

**Comment by gto90** [comment]
> I'm not 100% sure this has been solved, or at least it has not been tested yet. (Compiling on a Silicon Mac with GUIX)
> 
> It might be okay but we should probably keep this open till we are certain.

Ahh, you are correct @saltedlolly , my apologies.  We do still need to validate with Guix.

**Comment by ycagel** [comment]
Thanks for double checking on this. Apologies on closing this issue as the frozen screen is a separate issue based on @Jongjan88's feedback.

**Comment by ghost** [comment]
> Thanks for double checking on this. Apologies on closing this issue as the frozen screen is a separate issue based on @Jongjan88's feedback.

Yes the frozen issue is a separate issue.. but this is about guix

**Comment by JaredTate** [comment]
I am GUIX building for m1 and regular apple as we speak this morning. Will post how it goes and m1 binary if it works:

```
env HOSTS='x86_64-apple-darwin arm64-apple-darwin' ./contrib/guix/guix-build
```
It took a bit to get the Xcode SDK configured again, such a pain in the arse.

![Screenshot 2024-03-14 at 11 05 22 AM](https://github.com/DigiByte-Core/digibyte/assets/13957390/2e32d564-bb69-4676-a258-7049dcaa22c2)

**Comment by JaredTate** [comment]
Looks like it worked, I just cant test the dmg for arm64.

![Screenshot 2024-03-14 at 12 06 42 PM](https://github.com/DigiByte-Core/digibyte/assets/13957390/73e2a1cb-cea3-4563-bba1-8c2fd682421b)


IT won't let me upload a DMG.
![Screenshot 2024-03-14 at 12 03 30 PM](https://github.com/DigiByte-Core/digibyte/assets/13957390/2f2352ec-ac08-4f9e-a6d9-8eda459c2e3d)

So here it is on my proton drive:
https://drive.proton.me/urls/CBWAPJ6RZW#hzD1PXhuOWdf
