### ISSUE TITLE
The mainnet seeder at seed.digibyte.org is OFFLINE

### ISSUE THREAD

**Issue by saltedlolly** [DigiByte-Core/digibyte#135]
This issue is actually more critical for 7.17.3 though 8.22.x is also affected. In 7.17.3 without this seeder, there is currently only one working seeder for mainnet operated by @JaredTate - seed.digibyte.io. If Jared's goes offline we have no working seeders for 7.17.3. (Side note: there are currently NO working testnet seeders in 7.17.3. All the existing ones seem to have gone offline so new nodes have to be added to the network manualy.)

I have been asking around for several months to try and find out who owns the digibyte.org domain, and who maintains the seed.digibyte.org seeder. It was working a few months ago but now seems to be permanently offline. Can anyone help identify who maintains it? The source code says "Website Collective" which is not a lot to go on.

We have added a lot of new seeders in 8.22.x but it would be good to find out who manages this seeder, and if possible get it working. If we are unable to do either of these things, we can find someone else to run a seeder and remove it from the v8 codebase.

If v8 is still a long way off, I am of the opinion that we should urgently put together an interim 7.17.4 release that simply replaces the existing seeders with the new ones we have got setup for v8. This would ensure that new nodes can continue to join the network automatically.

**Do you know who is operating the seed.digibyte.org seeder?**

**If this is you, can you get it up and running again?**

**Comment by JaredTate** [comment]
I have no idea who owns the digibyte.org domain. it is not me. For the past several months I have been watching and running seed.digibyte.io directly in a terminal on my desktop to watch it. I spent an hour this morning writing a custom script to keep it running no matter what happens on the server. In the past, we have had issues with cron jobs, systemd and nohup on AWS servers because of security/ports/permissions config. It seems like it's working with 100% uptime now, I have put it through the wringer with reboots and killing the process, but I will watch it closely this week.

If I remember the thought process, we added seed.digibyte.org thinking whoever ran the digibyte.org website could also run a seed node, as it makes sense for that to become the main seed node as digibyte.io is retired. But as you mention the .io is only seed for 7.17.3 which is why I never have yet to migrate the server away from AWS. So I don't think there was any ever set up for the .org. The plan was someone would set it up once we found out who owned the .org.

**Comment by Sbosvk** [comment]
I guess technically DGBAT owns the org domain. I am lifting the discussion of running a seeder with the team. I think Jared is correct, I don't believe one was ever set up for org, but one definitely should be.

**Comment by saltedlolly** [comment]
I am pretty sure it was working a few months ago, because I remember testing it. (It presumably would never have been added to the code had it not been working at some point.) I don't know exactly when it went offline but I noticed recently that it was no longer working.

Perhaps if we could find the PR of when it was added, we might know who added it? At the end of the day, if we can get it up and running it would solve the problem with 7.17.3 as well. It would also be nice to have DGBAT running one.

**Comment by saltedlolly** [comment]
I think I found it: https://github.com/DigiByte-Core/digibyte/commit/c976edf1c9dccf45fc350bc1521f3fe3e7ae0a81

Not much help unfortunately. I don't believe Josiah was ever running it because I asked him a while back, and even if he was then, he clearly hasn't been doing so for a while.

**Comment by saltedlolly** [comment]
@JaredTate it's helpful to learn that your seeder is hosted on AWS. @mctrivia was trying to get a new seeder running on his AWS instance a few months back but couldn't make it work. I tried to help but was also stumped. I have previously written step-by-step instructions which worked fine on DigitalOcean and other VPS providers but didn't seem to work with AWS. If I was to guess it was a port or permission issue.

These are the instructions I put together: https://www.evernote.com/shard/s20/sh/46de28c1-9066-4ca5-8048-6f29f9e3bf52/66077e0b3f969350ebefe4228d731425

Would you be able to let me know what is missing to get it working on AWS? I can then update the instructions.

**Comment by JaredTate** [comment]
Thats a great guide @saltedlolly. Thanks for putting that together, the only thing I can see that's different is I could never get it to stay up as a cron job. Ended up using systemd and what finally did it for me equated basically to a double sudo. 

Once I could manually run the seeder with all the AWS firewall, ports & permissions set with the command:

`sudo ./dnsseed -h seed.digibyte.io -n dnsseed.digibyte.io -m jared@digibyte.io -a 172.26.14.66`

I created a systemd service:
`sudo nano /etc/systemd/system/dnsseed.service`

My systemd file looks like:
```[Unit]
Description=DNS Seeder for DigiByte
After=network.target

[Service]
ExecStart=/usr/bin/sudo /home/ubuntu/digibyte-seeder/dnsseed -h seed.digibyte.io -n dnsseed.digibyte.io -m jared@digibyte.io -a 172.26.14.66
Restart=always
# The configuration file application.properties should be here:
#change this to your workspace
WorkingDirectory=/home/ubuntu/digibyte-seeder
# Our other scripts had permission to run.
PermissionsStartOnly=true
# Allow the process to allocate a lot of memory
LimitNOFILE=4096

[Install]
WantedBy=multi-user.target
```

Then reloaded it & started it:
`sudo systemctl daemon-reload & sudo systemctl start dnsseed.service
`

What finally made it work was adding "/usr/bin/sudo" to ExecStart to run with sudo. By default, execstart is supposed to run as root, but it wasn't. Just adding "sudo" didn't work either.

**Comment by JaredTate** [comment]
Oh and had to make sure the seeder is executable with the right permissions & folder permissions.

**Comment by Sbosvk** [comment]
This issue can be closed. DNS Seeder on seed.DigiByte.org is back up and running.

**Comment by ycagel** [comment]
Thanks for your efforts @Sbosvk!

**Comment by JohnnyLawDGB** [comment]
Missed that you re-opened this @ycagel .  Are we needing another seeder spun up for seed.digibyte.org to point to?

**Comment by saltedlolly** [comment]
@JohnnyLawDGB seed.digibyte.org is still not working - @Sbosvk  tried but he can't get it working with his provider. It is not essential - we could always remove it if no one can get it working. That said it might be good to find someone else to run a seeder. It should really be someone who does not already run one. I still think it is a good idea to not have any one individual in charge of more that one mainnet and testnet seeder.

I would love to see a mainnet seeder added in Asia (Singapore, Japan, HK would all be good choices). Alternatively, we don't have any in Africa or South America so they would be a good choice.

**Comment by ycagel** [comment]
Has this been resolved? If so, let's close this out.

**Comment by saltedlolly** [comment]
Seed.digibyte.org still does not work

I will make a PR to remove it from DigiByte Core.

**Comment by JohnnyLawDGB** [comment]
> @JohnnyLawDGB seed.digibyte.org is still not working - @Sbosvk tried but he can't get it working with his provider. It is not essential - we could always remove it if no one can get it working. That said it might be good to find someone else to run a seeder. It should really be someone who does not already run one. I still think it is a good idea to not have any one individual in charge of more that one mainnet and testnet seeder.
> 
> I would love to see a mainnet seeder added in Asia (Singapore, Japan, HK would all be good choices). Alternatively, we don't have any in Africa or South America so they would be a good choice.

@RenzoDD is looking into setting one up now.  He is based in South America.
