### ISSUE TITLE
Chain syncing/forking issue between 7.17.3 and 8.22.0-rc2 on testnet

### ISSUE THREAD

**Issue by saltedlolly** [DigiByte-Core/digibyte#155]
This issue is difficult to explain, especially for a non-developer who does not understand the inner workings of the codebase, but I will try. All I can say for sure is that there definitely IS a problem, so please take this issue seriously, even if my assumptions are wrong.

In recent weeks we have been trying to get the testnet into a better state by getting more nodes online. With some people running 7.17.3/7.17.2 and others running 8.22.0-rc2 (or the rc3 preview with fast start), we discovered that there is a fork, though we have struggled to understand both why it happened, and why the nodes on the chain with less work were not automatically reverting to other chain as you would expect. We thought that perhaps this was caused by the fact that the chain had stalled the other week due to there being no miners, but it seems that there is something else going on to cause this.

What we noticed was that there were some nodes stuck on a shorter chain that is currently stalled at block height 2,444,197 and that there seem to be other nodes syncing to 2,7xx,xxx (and climbing). All nodes seemed to be stuck on their respective chain. To try and repair the fork we first resorted to downloading the shorter chain data and bootstapping the other nodes from it. At the time @Zulupool was mining on this chain, and this is the one the testnet block explorer was on. He was running the fast start version of 8.22.0 and had been since the summer. But he was still on the short chain. (perhaps because he had been running on it since before the block height that causes the issue). Trying to persuade other nodes to sync with his shorter chain failed.

We then instead had everyone try and sync from scratch to the longer chain. Zulupool stopped mining the short chian, deleted the blockchain data, and resynced to the longer chain. He then began mining on that one. New nodes running 8.22.0-rc2 all seemed to sync automatically with this longer chain, but older nodes running 7.17.x remained stuck on the shorter chain. I am pretty sure (though not positive) that we are seeing new nodes running 7.17.x syncing organically to the shorter chain and new nodes running 8.22.0-rcx syncing to the longer chain. You can see below that we now have more nodes running 8.22.0-rcx on the long chain than nodes on the shorter chain running 7.17.x

![Screenshot 2023-12-27 at 9 19 25 pm](https://github.com/DigiByte-Core/digibyte/assets/642592/8b390a6b-1619-4623-8288-f6ae8f6c7482)

In the last 24 hours several of us have now tried to sync a 7.17.3 node from scratch, to see if we could force them to use the longer chain. Given that 7.17.3 running testnet has no working seeders, the only way to get it to start syncing is to manually add an existing node.  We have tried to add only existing nodes on the long chain by putting this in digibyte.conf:

```
[test]

connect=198.58.124.101:12026
connect=157.245.63.215:12026
connect=116.202.241.54:12026
connect=80.123.84.18:12026
connect=80.122.107.230:12026
connect=80.122.142.86:12026
```

At least two nodes running 7.17.3 have failed to sync to the longer chain. They reach a certain point and stop. The node I synced yesterday is now stuck at block height 2,438,506. It appears to go no further. Others have had their node sync to approximately this height as well (though not always exactly the same height. Please see the chat in the DigiByte Discord here: https://discordapp.com/channels/878200503815782400/1133815334013509764 

My debug.log file now just repeats:
```2023-12-27T21:12:09Z ERROR: AcceptBlockHeader: prev block invalid```

Similarly @dangb048 on Discord has synced his node to 2,438,595 and debug.log is also saying "prev block invalid" like mine.

His other testnet node had finished syncing headers and was trying to sync blocks. The debg log says:

```
2023-12-27T16:15:32Z UpdateTip: new best=d2219d9029412babde7415caa530a3fd44bced48001dbaffb89642fd732149a2 height=2438594 version=0x20000002 algo=1 (scrypt) log2_work=50.854723 tx=2729902 date='2023-08-31T21:12:34Z' progress=0.021502 cache=451.1MiB(2599378txo)
2023-12-27T16:15:32Z block height for reward is 2438595
2023-12-27T16:15:32Z UpdateTip: new best=ce4ea8dc58a2121bc18fd512a1ef3c084ba922d88218a51a767c9ca3a2678064 height=2438595 version=0x20000002 algo=1 (scrypt) log2_work=50.854723 tx=2729903 date='2023-08-31T21:13:05Z' progress=0.021502 cache=451.1MiB(2599380txo)
2023-12-27T16:15:32Z Pre-allocating up to position 0x7000000 in blk00005.dat
2023-12-27T16:15:32Z ERROR: ConnectBlock: Consensus::CheckTxInputs: aab14bf168e90f8f27682a430e3ad12cdf195bb9a7ae2b1fba8c8b758a2f7f87, bad-txns-premature-spend-of-coinbase, tried to spend coinbase at depth 79 (code 16)
2023-12-27T16:15:32Z InvalidChainFound: invalid block=517d2751438a83ec26d74b7037d394e3777250d42f48d23836829d25f1c0d705  height=2438596  log2_work=50.854723  date=2023-08-31T21:14:40Z
2023-12-27T16:15:32Z InvalidChainFound:  current best=ce4ea8dc58a2121bc18fd512a1ef3c084ba922d88218a51a767c9ca3a2678064  height=2438595  log2_work=50.854723  date=2023-08-31T21:13:05Z
2023-12-27T16:15:32Z ERROR: ConnectTip(): ConnectBlock 517d2751438a83ec26d74b7037d394e3777250d42f48d23836829d25f1c0d705 failed
2023-12-27T16:15:32Z InvalidChainFound: invalid block=957ae573086a2ee26fe2d3d0704bf7c5e78b8947d8e6f288fcd92af110f8f97a  height=2438600  log2_work=50.854724  date=2023-08-31T21:17:04Z
2023-12-27T16:15:32Z InvalidChainFound:  current best=ce4ea8dc58a2121bc18fd512a1ef3c084ba922d88218a51a767c9ca3a2678064  height=2438595  log2_work=50.854723  date=2023-08-31T21:13:05Z
2023-12-27T16:15:46Z ERROR: AcceptBlockHeader: prev block invalid
```

Are we witnessing an unintended hard fork? I don't know but there is definitely something strange happening. I would appreciate everyone's assistance to get to the bottom of this. We obviously do not want to experience something similar happening on mainnet.

**Comment by ghost** [comment]
All the testnet nodes 7.17.x atm i see have this problem.
![problem7](https://github.com/DigiByte-Core/digibyte/assets/125610144/c8d99168-ddc3-4f37-8571-8b4872adf324)

**Comment by saltedlolly** [comment]
If anyone wants to recreate this you can try syncing a testnet node running 7.17.3 yourself. You will need to manually add an existing peer to get it to start syncing. If you sucesssfully syncs to the longer chain please let us know.

**Comment by barrystyle** [comment]
There appears to have been a large jump in blocks around August 31 to November this year on the chain with less blocks.

![image](https://github.com/DigiByte-Core/digibyte/assets/14147070/582af6e6-eb56-4cfa-8911-ae8b81f2b992)

**Comment by barrystyle** [comment]
> His other testnet node had finished syncing headers and was trying to sync blocks. The debg log says:
> 
> ```
> 2023-12-27T16:15:32Z UpdateTip: new best=d2219d9029412babde7415caa530a3fd44bced48001dbaffb89642fd732149a2 height=2438594 version=0x20000002 algo=1 (scrypt) log2_work=50.854723 tx=2729902 date='2023-08-31T21:12:34Z' progress=0.021502 cache=451.1MiB(2599378txo)
> 2023-12-27T16:15:32Z block height for reward is 2438595
> 2023-12-27T16:15:32Z UpdateTip: new best=ce4ea8dc58a2121bc18fd512a1ef3c084ba922d88218a51a767c9ca3a2678064 height=2438595 version=0x20000002 algo=1 (scrypt) log2_work=50.854723 tx=2729903 date='2023-08-31T21:13:05Z' progress=0.021502 cache=451.1MiB(2599380txo)
> 2023-12-27T16:15:32Z Pre-allocating up to position 0x7000000 in blk00005.dat
> 2023-12-27T16:15:32Z ERROR: ConnectBlock: Consensus::CheckTxInputs: aab14bf168e90f8f27682a430e3ad12cdf195bb9a7ae2b1fba8c8b758a2f7f87, bad-txns-premature-spend-of-coinbase, tried to spend coinbase at depth 79 (code 16)
> 2023-12-27T16:15:32Z InvalidChainFound: invalid block=517d2751438a83ec26d74b7037d394e3777250d42f48d23836829d25f1c0d705  height=2438596  log2_work=50.854723  date=2023-08-31T21:14:40Z
> 2023-12-27T16:15:32Z InvalidChainFound:  current best=ce4ea8dc58a2121bc18fd512a1ef3c084ba922d88218a51a767c9ca3a2678064  height=2438595  log2_work=50.854723  date=2023-08-31T21:13:05Z
> 2023-12-27T16:15:32Z ERROR: ConnectTip(): ConnectBlock 517d2751438a83ec26d74b7037d394e3777250d42f48d23836829d25f1c0d705 failed
> 2023-12-27T16:15:32Z InvalidChainFound: invalid block=957ae573086a2ee26fe2d3d0704bf7c5e78b8947d8e6f288fcd92af110f8f97a  height=2438600  log2_work=50.854724  date=2023-08-31T21:17:04Z
> 2023-12-27T16:15:32Z InvalidChainFound:  current best=ce4ea8dc58a2121bc18fd512a1ef3c084ba922d88218a51a767c9ca3a2678064  height=2438595  log2_work=50.854723  date=2023-08-31T21:13:05Z
> 2023-12-27T16:15:46Z ERROR: AcceptBlockHeader: prev block invalid
> ```

A quick glance suggests that perhaps COINBASE_MATURITY isn't being respected between environments (https://github.com/DigiByte-Core/digibyte/blob/develop/src/consensus/consensus.h#L21C18-L22).

**Comment by barrystyle** [comment]
https://github.com/DigiByte-Core/digibyte/pull/157

**Comment by JaredTate** [comment]
Thanks for the detective work @saltedlolly @Jongjan88. I think @barrystyle is on to the fix here with https://github.com/DigiByte-Core/digibyte/pull/157 and missing/ improper `COINBASE_MATURITY_2` code.

**Comment by ycagel** [comment]
@saltedlolly Can you run the binaries and see if this issue has been resolved? With the recent PRs that were merged, can this issue be closed?

**Comment by ghost** [comment]
This problem has been solved. I mined on all 5 algos and made a lot of transactions to test this. 

I hope we can make fast a Release candidate 3 @JaredTate 
https://github.com/DigiByte-Core/digibyte/issues/162#issuecomment-1915654420

And after that if possible remove the binaries from RC1 & RC2. @saltedlolly
https://github.com/DigiByte-Core/digibyte/issues/162#issue-2104390613

**Comment by saltedlolly** [comment]
I have just tested this by loading up the test binary with the "bad" chain. It immediately switched to the 7.17.3 chain and synced correctly. @Jongjan88 has also done the same. I think we can conclude that any nodes that run this version will revert to the correct 7.17.3 chain essential "unforking". I am marking this issue as resolved. Great news!

![Screenshot 2024-01-31 at 11 39 56 pm](https://github.com/DigiByte-Core/digibyte/assets/642592/2ec05faa-1120-40cb-9fe9-a4fcc1cbfa0c)
