### ISSUE TITLE
WALLET_INCREMENTAL_RELAY_FEE

### ISSUE THREAD

**Issue by ghost** [DigiByte-Core/digibyte#158]
#https://github.com/DigiByte-Core/digibyte/blob/archive/7.17.2/src/wallet/wallet.h
**Digibyte 7.17.2**
_LINE 54:_
//! minimum recommended increment for BIP 125 replacement txs
static const CAmount WALLET_INCREMENTAL_RELAY_FEE = 5000;

#https://github.com/bitcoin/bitcoin/blob/23.x/src/wallet/wallet.h
**Bitcoin 23,24,25,26**
_LINE 95:_
//! minimum recommended increment for BIP 125 replacement txs
static const CAmount WALLET_INCREMENTAL_RELAY_FEE = 5000;

#https://github.com/DigiByte-Core/digibyte/blob/develop/src/wallet/wallet.h
**Digibyte Dev**
_LINE 86:_
//! minimum recommended increment for BIP 125 replacement txs
static const CAmount WALLET_INCREMENTAL_RELAY_FEE = 1000000;

---------------------------------------------------------------------------------------------

**WALLET_INCREMENTAL_RELAY_FEE**
From 5.000 to 1.000.000?

**Comment by saltedlolly** [comment]
Was this change intentional?
