### ISSUE TITLE
bech32 signatures malformed

### ISSUE THREAD

**Issue by mctrivia** [DigiByte-Core/digibyte#16]
If you sign a message using a bech32 address the resulting signature does not have the segwit flag set so it fails tests using message signature libraries.

**Comment by SmartArray** [comment]
Can you give an example please?

**Comment by mctrivia** [comment]
Turns out there is no bug the feature is just missing entirely.  As a result to do it I did dumpprivkey then signed using the private key.

This method works except existing libraries expect the first byte of header to include encoding of what address type was used

https://github.com/bitcoinjs/bitcoinjs-message/blob/master/index.js#L37

For my own uses I wrote a hack library that just checks first 4 letters of address and ignores the header.  But for future would be nice if wallet had the option to sign bech32 addresses in one step and added correct header.

**Comment by ycagel** [comment]
Based on the dialogue above, this is not a bug.
