### ISSUE TITLE
Coinbase Maturity

### ISSUE THREAD

**Issue by ycagel** [DigiByte-Core/digibyte#161]
Awesome you found this @barrystyle ! Thanks for the contribution. It looks like there might be a couple of other places where `COINBASE_MATURITY_2` needs added properly to fix the issue as @beggsdl mentioned above. 

txmempool.cpp needs an additional `COINBASE_MATURITY_2` entry: https://github.com/DigiByte-Core/digibyte/blob/1c2c6563b6d5e5170cb2fa85a7564657b4d91271/src/txmempool.cpp#L535-L538

Here is txmempool.cpp `COINBASE_MATURITY_2` in 7.17.3:
https://github.com/DigiByte-Core/digibyte/blob/258afaceba07a16b8cf3acefc5bf2ce70d213b68/src/txmempool.cpp#L522-L529

Also in src/wallet/wallet.cpp looks like we need change to `COINBASE_MATURITY_2` as well: https://github.com/DigiByte-Core/digibyte/blob/1c2c6563b6d5e5170cb2fa85a7564657b4d91271/src/wallet/wallet.cpp#L2904-L2911

Here is what 7.17.3 shows: https://github.com/DigiByte-Core/digibyte/blob/258afaceba07a16b8cf3acefc5bf2ce70d213b68/src/wallet/wallet.cpp#L4419-L4426

V7.17.3 mentions `COINBASE_MATURITY_2` in these locations: 
![Screenshot 2024-01-08 at 12 09 48 PM](https://github.com/DigiByte-Core/digibyte/assets/13957390/dfaa4d5b-4daa-4903-87e3-4199f8c8065c)

current 8.22 including this PR onlys shows `COINBASE_MATURITY_2` in 3 places outside of tests:
![Screenshot 2024-01-08 at 12 10 57 PM](https://github.com/DigiByte-Core/digibyte/assets/13957390/e0d0accf-974b-4d57-82b2-4111d0aacc81)

I can add additions on to this PR @barrystyle or you can modify yours. Just let me know.

_Originally posted by @JaredTate in https://github.com/DigiByte-Core/digibyte/issues/157#issuecomment-1881677700_

**Comment by JaredTate** [comment]
This should be resolved with https://github.com/DigiByte-Core/digibyte/pull/160
