### ISSUE TITLE
Manually Selecting 15+ TX Inputs Throws TX FEE Error, Can't De-Dust Wallet

### ISSUE THREAD

**Issue by JaredTate** [DigiByte-Core/digibyte#163]
When using coin control & selecting 15 or more manual inputs, the QT core wallet throws a TX error. We don't have the fee rates set correctly.
![Screenshot 2024-01-29 at 3 16 01 PM](https://github.com/DigiByte-Core/digibyte/assets/13957390/06bd7150-e19d-411b-88e8-bda7fc298780)
![Screenshot 2024-01-29 at 3 16 10 PM](https://github.com/DigiByte-Core/digibyte/assets/13957390/4cd214ab-318e-4a26-a3e4-c6dcf08d9304)
![Screenshot 2024-01-29 at 3 16 59 PM](https://github.com/DigiByte-Core/digibyte/assets/13957390/bb282c26-e68e-4d9d-ae0b-24cfa5eeecb4)

The error is defined here in code: https://github.com/DigiByte-Core/digibyte/blob/e8247b0d596a443eb75f7bd6a9760534970eb25d/src/util/error.cpp#L32-L33

It looks like the bug is now in `MAX_FEE_EXCEEDED`
Well, the bug is the fee rates we just changed most likely. Should be an easy fix, just need to calculate all the fee rates correctly.
`MAX_FEE_EXCEEDED` is defined here:
https://github.com/DigiByte-Core/digibyte/blob/e8247b0d596a443eb75f7bd6a9760534970eb25d/src/node/transaction.cpp#L67-L78

**Comment by Jongjan88** [comment]
**src/wallet/wallet.h**

constexpr CAmount DEFAULT_TRANSACTION_MAXFEE{COIN / 10};
to
constexpr CAmount DEFAULT_TRANSACTION_MAXFEE{COIN * 10};

After I changed this it worked for me. Don't know if this is the correct solution.

**Comment by ghost** [comment]
Dev branch
https://github.com/DigiByte-Core/digibyte/blob/e8247b0d596a443eb75f7bd6a9760534970eb25d/src/wallet/wallet.h#L99-L104

![Screenshot from 2024-01-30 23-12-41](https://github.com/DigiByte-Core/digibyte/assets/125610144/0fab3d14-5548-4a0d-a484-a3a3d625fae0)
----------------------------------------
**DEFAULT_TRANSACTION_MAXFEE** From **_COIN /10_** to **_COIN_**
**HIGH_MAX_TX_FEE** from **_100_** to **_1000_**


//! -maxtxfee default
constexpr CAmount DEFAULT_TRANSACTION_MAXFEE{COIN};

//! -maxtxfee will warn if called with a higher fee than this amount (in satoshis)
constexpr CAmount HIGH_MAX_TX_FEE{1000 * HIGH_TX_FEE_PER_KB};


![Screenshot from 2024-01-30 23-10-13](https://github.com/DigiByte-Core/digibyte/assets/125610144/a1105448-e42a-4e21-93f3-1e992d099c35)

**Comment by JaredTate** [comment]
Fixed with https://github.com/DigiByte-Core/digibyte/pull/165
