### ISSUE TITLE
Minimum tx fee per kb and maxfee issue

### ISSUE THREAD

**Issue by beggsdl** [DigiByte-Core/digibyte#169]
Running 8.22.0-rc3 n testnet on Windows 10.

The release notes for RC3 state this: "Minimum Transaction Fee Increase: The minimum transaction fee has been increased from 0.001 DGB to 0.1 DGB per kilobyte."

I tried to spend 1million DGB with a fee/kB of 0.1 (supposedly new new minimum tx fee/kB), but received this error (I do not have -maxfee set in config file):
![image](https://github.com/DigiByte-Core/digibyte/assets/35427422/3e67769c-e6f3-4379-b99e-6ed20ca51038)

I then changed the fee/kb to 0.01 (which is now below the new minimum tx fee/kB) and the tx was going to work:
![image](https://github.com/DigiByte-Core/digibyte/assets/35427422/d005e1b8-61bc-4779-9e3e-311816f5c1b0)

You will also notice that the total transaction fee is only 0.00208 DGB, which is far less than the 10 DGB max from #159.
Which, seeing that the tx size is only 0.208 kB, the total fee at the fee/kB rate of 0.1 would still only be 0.0208 DGB.  So why did the first attempt not work?

**Comment by JaredTate** [comment]
Looks like same issue I had run into, but I only tested up to 50 inputs. When I did 60 inputs I was able to recreate the problem.  Looks like https://github.com/DigiByte-Core/digibyte/pull/171 does fix this. I just tested it.

**Comment by ycagel** [comment]
https://github.com/DigiByte-Core/digibyte/pull/171 has addressed this and been merged.
