### ISSUE TITLE
71 out of 216 Functional Tests Now Failing

### ISSUE THREAD

**Issue by JaredTate** [DigiByte-Core/digibyte#173]
Looks like we got a bit ahead of ourselves by not fixing tests on every PR in the last few months. I had issues getting my Python dev environment set up after upgrading to the latest macOS a few weeks ago, so I just now was able to get around fixing it and getting functional tests to run for me. It would be great to have someone else get the same failure results. Most of these failures are likely to do Fees in the test environment, and a few other changes we recently made. Should not be hard, just time-consuming to fix them all. Definitely something we need to do. It could reveal a few more bugs to squash.

I know there are some fixes already being worked on with https://github.com/DigiByte-Core/digibyte/issues/172

To compile for tests:
`./autogen.sh ` 
`./configure --enable-debug` 
`make ` 

After compiling locally you can run the following:
`make check` 

Then run:
`test/functional/test_runner.py`

Note: it can take hours for these tests to run.

To speed it up run & adjust # of jobs... too high and you get more failures. I have an 8-core CPU and run 6 jobs at a time:
`test/functional/test_runner.py --extended --jobs=6`

```feature_assumevalid.py                             | ✖ Failed  | 470 s
feature_coinstatsindex.py                          | ✖ Failed  | 22 s
feature_config_args.py                             | ✖ Failed  | 16 s
feature_pruning.py                                 | ✖ Failed  | 799 s
feature_taproot.py                                 | ✖ Failed  | 21 s
interface_digibyte_cli.py                          | ✖ Failed  | 16 s
mempool_unbroadcast.py                             | ✖ Failed  | 28 s
mining_basic.py                                    | ✖ Failed  | 75 s
p2p_addr_relay.py                                  | ✖ Failed  | 6 s
p2p_compactblocks.py                               | ✖ Failed  | 5 s
rpc_blockchain.py                                  | ✖ Failed  | 39 s
rpc_createmultisig.py --descriptors                | ✖ Failed  | 62 s
rpc_createmultisig.py --legacy-wallet              | ✖ Failed  | 108 s
rpc_fundrawtransaction.py --descriptors            | ✖ Failed  | 2 s
rpc_fundrawtransaction.py --legacy-wallet          | ✖ Failed  | 9 s
rpc_psbt.py --descriptors                          | ✖ Failed  | 18 s
rpc_psbt.py --legacy-wallet                        | ✖ Failed  | 32 s
rpc_rawtransaction.py --descriptors                | ✖ Failed  | 21 s
rpc_rawtransaction.py --legacy-wallet              | ✖ Failed  | 26 s
rpc_signrawtransaction.py --descriptors            | ✖ Failed  | 11 s
rpc_signrawtransaction.py --legacy-wallet          | ✖ Failed  | 13 s
wallet_abandonconflict.py --descriptors            | ✖ Failed  | 29 s
wallet_abandonconflict.py --legacy-wallet          | ✖ Failed  | 38 s
wallet_avoidreuse.py --descriptors                 | ✖ Failed  | 39 s
wallet_avoidreuse.py --legacy-wallet               | ✖ Failed  | 40 s
wallet_backup.py --descriptors                     | ✖ Failed  | 19 s
wallet_backup.py --legacy-wallet                   | ✖ Failed  | 24 s
wallet_balance.py --descriptors                    | ✖ Failed  | 11 s
wallet_balance.py --legacy-wallet                  | ✖ Failed  | 13 s
wallet_basic.py --descriptors                      | ✖ Failed  | 6 s
wallet_basic.py --legacy-wallet                    | ✖ Failed  | 11 s
wallet_bumpfee.py --descriptors                    | ✖ Failed  | 13 s
wallet_bumpfee.py --legacy-wallet                  | ✖ Failed  | 15 s
wallet_coinbase_category.py --descriptors          | ✖ Failed  | 8 s
wallet_coinbase_category.py --legacy-wallet        | ✖ Failed  | 10 s
wallet_create_tx.py --descriptors                  | ✖ Failed  | 92 s
wallet_create_tx.py --legacy-wallet                | ✖ Failed  | 180 s
wallet_descriptor.py --descriptors                 | ✖ Failed  | 7 s
wallet_fallbackfee.py --descriptors                | ✖ Failed  | 5 s
wallet_fallbackfee.py --legacy-wallet              | ✖ Failed  | 6 s
wallet_groups.py --descriptors                     | ✖ Failed  | 14 s
wallet_groups.py --legacy-wallet                   | ✖ Failed  | 28 s
wallet_hd.py --descriptors                         | ✖ Failed  | 15 s
wallet_hd.py --legacy-wallet                       | ✖ Failed  | 17 s
wallet_importdescriptors.py --descriptors          | ✖ Failed  | 19 s
wallet_importmulti.py --legacy-wallet              | ✖ Failed  | 22 s
wallet_importprunedfunds.py --descriptors          | ✖ Failed  | 7 s
wallet_importprunedfunds.py --legacy-wallet        | ✖ Failed  | 10 s
wallet_keypool.py --descriptors                    | ✖ Failed  | 9 s
wallet_keypool.py --legacy-wallet                  | ✖ Failed  | 18 s
wallet_keypool_topup.py --descriptors              | ✖ Failed  | 24 s
wallet_keypool_topup.py --legacy-wallet            | ✖ Failed  | 75 s
wallet_labels.py --descriptors                     | ✖ Failed  | 2 s
wallet_labels.py --legacy-wallet                   | ✖ Failed  | 4 s
wallet_listsinceblock.py --descriptors             | ✖ Failed  | 12 s
wallet_listsinceblock.py --legacy-wallet           | ✖ Failed  | 24 s
wallet_multiwallet.py --descriptors                | ✖ Failed  | 55 s
wallet_multiwallet.py --legacy-wallet              | ✖ Failed  | 98 s
wallet_multiwallet.py --usecli                     | ✖ Failed  | 111 s
wallet_orphanedreward.py                           | ✖ Failed  | 11 s
wallet_send.py --descriptors                       | ✖ Failed  | 20 s
wallet_send.py --legacy-wallet                     | ✖ Failed  | 50 s
wallet_taproot.py                                  | ✖ Failed  | 13 s
wallet_txn_clone.py                                | ✖ Failed  | 19 s
wallet_txn_clone.py --mineblock                    | ✖ Failed  | 15 s
wallet_txn_clone.py --segwit                       | ✖ Failed  | 20 s
wallet_txn_doublespend.py --descriptors            | ✖ Failed  | 11 s
wallet_txn_doublespend.py --legacy-wallet          | ✖ Failed  | 15 s
wallet_txn_doublespend.py --mineblock              | ✖ Failed  | 19 s
wallet_watchonly.py --legacy-wallet                | ✖ Failed  | 21 s
wallet_watchonly.py --usecli --legacy-wallet       | ✖ Failed  | 22 s
ALL                                                | ✖ Failed  | 14782 s (accumulated) ```

**Comment by Jongjan88** [comment]
example_test.py                                    | ✖ Failed  | 8 s
feature_assumevalid.py                             | ✖ Failed  | 8 s
feature_bip68_sequence.py                          | ✖ Failed  | 47 s
feature_block.py                                   | ✖ Failed  | 3 s
feature_cltv.py                                    | ✖ Failed  | 6 s
feature_coinstatsindex.py                          | ✖ Failed  | 6 s
feature_csv_activation.py                          | ✖ Failed  | 4 s
feature_dersig.py                                  | ✖ Failed  | 6 s
feature_maxuploadtarget.py                         | ✖ Failed  | 4 s
feature_nulldummy.py --descriptors                 | ✖ Failed  | 7 s
feature_nulldummy.py --legacy-wallet               | ✖ Failed  | 7 s
feature_pruning.py                                 | ✖ Failed  | 7 s
feature_taproot.py                                 | ✖ Failed  | 6 s
feature_versionbits_warning.py                     | ✖ Failed  | 7 s
interface_digibyte_cli.py                          | ✖ Failed  | 5 s
mempool_unbroadcast.py                             | ✖ Failed  | 6 s
mining_basic.py                                    | ✖ Failed  | 7 s
p2p_compactblocks.py                               | ✖ Failed  | 3 s
p2p_dos_header_tree.py                             | ✖ Failed  | 6 s
p2p_eviction.py                                    | ✖ Failed  | 7 s
p2p_filter.py                                      | ✖ Failed  | 8 s
p2p_fingerprint.py                                 | ✖ Failed  | 6 s
p2p_getdata.py                                     | ✖ Failed  | 7 s
p2p_invalid_block.py                               | ✖ Failed  | 8 s
p2p_invalid_locator.py                             | ✖ Failed  | 8 s
p2p_invalid_messages.py                            | ✖ Failed  | 8 s
p2p_invalid_tx.py                                  | ✖ Failed  | 8 s
p2p_node_network_limited.py                        | ✖ Failed  | 6 s
p2p_segwit.py                                      | ✖ Failed  | 9 s
p2p_sendheaders.py                                 | ✖ Failed  | 6 s
p2p_unrequested_blocks.py                          | ✖ Failed  | 5 s
rpc_blockchain.py                                  | ✖ Failed  | 6 s
rpc_createmultisig.py --descriptors                | ✖ Failed  | 15 s
rpc_createmultisig.py --legacy-wallet              | ✖ Failed  | 16 s
rpc_fundrawtransaction.py --descriptors            | ✖ Failed  | 2 s
rpc_fundrawtransaction.py --legacy-wallet          | ✖ Failed  | 5 s
rpc_psbt.py --descriptors                          | ✖ Failed  | 3 s
rpc_psbt.py --legacy-wallet                        | ✖ Failed  | 8 s
rpc_rawtransaction.py --descriptors                | ✖ Failed  | 6 s
rpc_rawtransaction.py --legacy-wallet              | ✖ Failed  | 6 s
rpc_signrawtransaction.py --descriptors            | ✖ Failed  | 3 s
rpc_signrawtransaction.py --legacy-wallet          | ✖ Failed  | 3 s
wallet_abandonconflict.py --descriptors            | ✖ Failed  | 13 s
wallet_abandonconflict.py --legacy-wallet          | ✖ Failed  | 12 s
wallet_avoidreuse.py --descriptors                 | ✖ Failed  | 4 s
wallet_avoidreuse.py --legacy-wallet               | ✖ Failed  | 7 s
wallet_backup.py --descriptors                     | ✖ Failed  | 5 s
wallet_backup.py --legacy-wallet                   | ✖ Failed  | 8 s
wallet_balance.py --descriptors                    | ✖ Failed  | 7 s
wallet_balance.py --legacy-wallet                  | ✖ Failed  | 7 s
wallet_basic.py --descriptors                      | ✖ Failed  | 6 s
wallet_basic.py --legacy-wallet                    | ✖ Failed  | 7 s
wallet_bumpfee.py --descriptors                    | ✖ Failed  | 7 s
wallet_bumpfee.py --legacy-wallet                  | ✖ Failed  | 7 s
wallet_coinbase_category.py --descriptors          | ✖ Failed  | 6 s
wallet_coinbase_category.py --legacy-wallet        | ✖ Failed  | 6 s
wallet_create_tx.py --descriptors                  | ✖ Failed  | 6 s
wallet_create_tx.py --legacy-wallet                | ✖ Failed  | 38 s
wallet_descriptor.py --descriptors                 | ✖ Failed  | 7 s
wallet_fallbackfee.py --descriptors                | ✖ Failed  | 6 s
wallet_fallbackfee.py --legacy-wallet              | ✖ Failed  | 6 s
wallet_groups.py --descriptors                     | ✖ Failed  | 7 s
wallet_groups.py --legacy-wallet                   | ✖ Failed  | 7 s
wallet_hd.py --descriptors                         | ✖ Failed  | 2 s
wallet_hd.py --legacy-wallet                       | ✖ Failed  | 4 s
wallet_importdescriptors.py --descriptors          | ✖ Failed  | 7 s
wallet_importmulti.py --legacy-wallet              | ✖ Failed  | 6 s
wallet_importprunedfunds.py --descriptors          | ✖ Failed  | 7 s
wallet_importprunedfunds.py --legacy-wallet        | ✖ Failed  | 7 s
wallet_keypool.py --descriptors                    | ✖ Failed  | 7 s
wallet_keypool.py --legacy-wallet                  | ✖ Failed  | 7 s
wallet_keypool_topup.py --descriptors              | ✖ Failed  | 4 s
wallet_keypool_topup.py --legacy-wallet            | ✖ Failed  | 17 s
wallet_labels.py --descriptors                     | ✖ Failed  | 8 s
wallet_labels.py --legacy-wallet                   | ✖ Failed  | 6 s
wallet_listsinceblock.py --descriptors             | ✖ Failed  | 6 s
wallet_listsinceblock.py --legacy-wallet           | ✖ Failed  | 6 s
wallet_multiwallet.py --descriptors                | ✖ Failed  | 11 s
wallet_multiwallet.py --legacy-wallet              | ✖ Failed  | 21 s
wallet_multiwallet.py --usecli                     | ✖ Failed  | 21 s
wallet_orphanedreward.py                           | ✖ Failed  | 6 s
wallet_resendwallettransactions.py --descriptors   | ✖ Failed  | 6 s
wallet_resendwallettransactions.py --legacy-wallet | ✖ Failed  | 6 s
wallet_send.py --descriptors                       | ✖ Failed  | 6 s
wallet_send.py --legacy-wallet                     | ✖ Failed  | 17 s
wallet_taproot.py                                  | ✖ Failed  | 6 s
wallet_txn_clone.py                                | ✖ Failed  | 3 s
wallet_txn_clone.py --mineblock                    | ✖ Failed  | 9 s
wallet_txn_clone.py --segwit                       | ✖ Failed  | 3 s
wallet_txn_doublespend.py --descriptors            | ✖ Failed  | 9 s
wallet_txn_doublespend.py --legacy-wallet          | ✖ Failed  | 9 s
wallet_txn_doublespend.py --mineblock              | ✖ Failed  | 3 s
wallet_watchonly.py --legacy-wallet                | ✖ Failed  | 4 s
wallet_watchonly.py --usecli --legacy-wallet       | ✖ Failed  | 4 s

ALL                                                | ✖ Failed  | 3017 s (accumulated) 
Runtime: 528 s

**94 failing**

**Comment by ghost** [comment]
![Screenshot from 2024-02-14 20-19-28](https://github.com/DigiByte-Core/digibyte/assets/125610144/382a0bd4-0a88-4e63-9d19-a346d2e12472)

Where can i find. digibyte_scrypt ? It is not in the DigiByte folder.

Update:
https://pypi.org/project/digibyte-scrypt/

**Comment by ghost** [comment]
```
feature_coinstatsindex.py                          | ✖ Failed  | 7 s
feature_taproot.py                                 | ✖ Failed  | 4 s
interface_digibyte_cli.py                          | ✖ Failed  | 4 s
mempool_unbroadcast.py                             | ✖ Failed  | 7 s
mining_basic.py                                    | ✖ Failed  | 6 s
p2p_compactblocks.py                               | ✖ Failed  | 5 s
rpc_blockchain.py                                  | ✖ Failed  | 7 s
rpc_createmultisig.py --descriptors                | ✖ Failed  | 11 s
rpc_createmultisig.py --legacy-wallet              | ✖ Failed  | 21 s
rpc_fundrawtransaction.py --descriptors            | ✖ Failed  | 2 s
rpc_fundrawtransaction.py --legacy-wallet          | ✖ Failed  | 4 s
rpc_psbt.py --descriptors                          | ✖ Failed  | 5 s
rpc_psbt.py --legacy-wallet                        | ✖ Failed  | 6 s
rpc_rawtransaction.py --descriptors                | ✖ Failed  | 6 s
rpc_rawtransaction.py --legacy-wallet              | ✖ Failed  | 6 s
rpc_signrawtransaction.py --descriptors            | ✖ Failed  | 6 s
rpc_signrawtransaction.py --legacy-wallet          | ✖ Failed  | 6 s
wallet_abandonconflict.py --descriptors            | ✖ Failed  | 12 s
wallet_abandonconflict.py --legacy-wallet          | ✖ Failed  | 8 s
wallet_avoidreuse.py --descriptors                 | ✖ Failed  | 4 s
wallet_avoidreuse.py --legacy-wallet               | ✖ Failed  | 7 s
wallet_backup.py --descriptors                     | ✖ Failed  | 5 s
wallet_backup.py --legacy-wallet                   | ✖ Failed  | 9 s
wallet_balance.py --descriptors                    | ✖ Failed  | 7 s
wallet_balance.py --legacy-wallet                  | ✖ Failed  | 7 s
wallet_basic.py --descriptors                      | ✖ Failed  | 3 s
wallet_basic.py --legacy-wallet                    | ✖ Failed  | 6 s
wallet_bumpfee.py --descriptors                    | ✖ Failed  | 6 s
wallet_bumpfee.py --legacy-wallet                  | ✖ Failed  | 6 s
wallet_coinbase_category.py --descriptors          | ✖ Failed  | 6 s
wallet_coinbase_category.py --legacy-wallet        | ✖ Failed  | 6 s
wallet_create_tx.py --descriptors                  | ✖ Failed  | 6 s
wallet_create_tx.py --legacy-wallet                | ✖ Failed  | 30 s
wallet_descriptor.py --descriptors                 | ✖ Failed  | 7 s
wallet_fallbackfee.py --descriptors                | ✖ Failed  | 7 s
wallet_fallbackfee.py --legacy-wallet              | ✖ Failed  | 7 s
wallet_groups.py --descriptors                     | ✖ Failed  | 6 s
wallet_groups.py --legacy-wallet                   | ✖ Failed  | 6 s
wallet_hd.py --descriptors                         | ✖ Failed  | 1 s
wallet_hd.py --legacy-wallet                       | ✖ Failed  | 4 s
wallet_importdescriptors.py --descriptors          | ✖ Failed  | 7 s
wallet_importmulti.py --legacy-wallet              | ✖ Failed  | 3 s
wallet_importprunedfunds.py --descriptors          | ✖ Failed  | 6 s
wallet_importprunedfunds.py --legacy-wallet        | ✖ Failed  | 6 s
wallet_keypool.py --descriptors                    | ✖ Failed  | 7 s
wallet_keypool.py --legacy-wallet                  | ✖ Failed  | 7 s
wallet_keypool_topup.py --descriptors              | ✖ Failed  | 3 s
wallet_keypool_topup.py --legacy-wallet            | ✖ Failed  | 14 s
wallet_labels.py --descriptors                     | ✖ Failed  | 3 s
wallet_labels.py --legacy-wallet                   | ✖ Failed  | 2 s
wallet_listsinceblock.py --descriptors             | ✖ Failed  | 6 s
wallet_listsinceblock.py --legacy-wallet           | ✖ Failed  | 6 s
wallet_multiwallet.py --descriptors                | ✖ Failed  | 9 s
wallet_multiwallet.py --legacy-wallet              | ✖ Failed  | 18 s
wallet_multiwallet.py --usecli                     | ✖ Failed  | 17 s
wallet_orphanedreward.py                           | ✖ Failed  | 7 s
wallet_send.py --descriptors                       | ✖ Failed  | 6 s
wallet_send.py --legacy-wallet                     | ✖ Failed  | 13 s
wallet_taproot.py                                  | ✖ Failed  | 6 s
wallet_txn_clone.py                                | ✖ Failed  | 3 s
wallet_txn_clone.py --mineblock                    | ✖ Failed  | 8 s
wallet_txn_clone.py --segwit                       | ✖ Failed  | 3 s
wallet_txn_doublespend.py --descriptors            | ✖ Failed  | 8 s
wallet_txn_doublespend.py --legacy-wallet          | ✖ Failed  | 7 s
wallet_txn_doublespend.py --mineblock              | ✖ Failed  | 3 s
wallet_watchonly.py --legacy-wallet                | ✖ Failed  | 4 s
wallet_watchonly.py --usecli --legacy-wallet       | ✖ Failed  | 6 s

ALL                                                | ✖ Failed  | 3187 s (accumulated) 
Runtime: 547 s
```

**Develop branch 67 errors.**


```
feature_pruning.py                                 | ✖ Failed  | 0 s
feature_taproot.py                                 | ✖ Failed  | 5 s
rpc_blockchain.py                                  | ✖ Failed  | 4 s
rpc_net.py                                         | ✖ Failed  | 7 s
wallet_taproot.py                                  | ✖ Failed  | 2 s

ALL                                                | ✖ Failed  | 3905 s (accumulated) 
Runtime: 567 s
```
**RC2 5 errors.**

**Comment by JaredTate** [comment]
This can be closed now. Fixed all failing tests.
