### ISSUE TITLE
Change all mention of satoshis/sats to something else

### ISSUE THREAD

**Issue by saltedlolly** [DigiByte-Core/digibyte#198]
![Screenshot 2024-03-14 at 7 01 01 pm](https://github.com/DigiByte-Core/digibyte/assets/642592/93c68b8f-81a0-484a-be83-f5ccd410d621)

I think we should agree on a term for the DigiByte equivalent of a Satoshi and stick to it.

We are not Bitcoin so I think we should avoid using the term sats or satoshis for the smallest denomination of DGB. It will only lead to confusion in the future. I believe these have been referred to as DigiSatoshis in the past which is a bit of a mouthful and in my opinion not a great name. I think we can do better.

Two ideas:

**digits** (**dits** for short) - a 'digit' can mean a number. https://www.dictionary.com/browse/digit 

**bits** - a 'bit' has been a term used with fiat money to refer to a small coin. e.g. Thrupenny bit: https://en.wikipedia.org/wiki/Threepence_(British_coin) It also connects with byte. 

I personally like bits but perhaps this is a bit too close to _Bit_-coin?

What do people think? Any other suggestions?

**Comment by saltedlolly** [comment]
I just noticed that uDGB is already using the name bits. I am not sure why that was called a 'bit'.

**Comment by beggsdl** [comment]
I have thought the same thing.

We currently have:
- DGB - DigiBytes
- mDGB - milli-DigiBytes - 1/1 000
- µDGB - micro-DigiBytes - bits - 1/1 000 000
- Satoshi - sat - 1/100 000 000

If we want to keep a connection to Satoshi, maybe Digitoshi (dig or digi).

In my opinion, digits or bits could cause confusion since those have other well known meanings.

**Comment by beggsdl** [comment]
> I just noticed that uDGB is already using the name bits. I am not sure what a udgb is.

In Windows, if you hover over each of the different units in the dropdown on the Send screen, it shows what each one is.  Same thing on the Display tab of the Options screen.

**Comment by beggsdl** [comment]
Here are a couple suggestions from ChatGPT:
- DigiSat: This term combines "Digi" from DigiByte with "Sat" from Satoshi, creating a unique identifier for the smallest unit of DigiByte.
- DigiBit: Similar to "DigiSat," this term combines "Digi" with "Bit" to represent the smallest fraction of DigiByte.
- Digi: Keeping it simple, you could refer to the smallest unit of DigiByte simply as "Digi," which is derived from the name of the cryptocurrency itself.

Maybe something like this:
- DGB - DigiBytes
- mDGB - milli-DigiBytes [milliDigi] - 1/1 000
- µDGB - micro-DigiBytes - [microDigi] - 1/1 000 000
- Digitoshi - [Digi] - 1/100 000 000

Just throwing out ideas...

**Comment by ghost** [comment]
Digitoshi - [Digi] Nice!!

**Comment by JaredTate** [comment]
> Here are a couple suggestions from ChatGPT:
> 
> * DigiSat: This term combines "Digi" from DigiByte with "Sat" from Satoshi, creating a unique identifier for the smallest unit of DigiByte.
> * DigiBit: Similar to "DigiSat," this term combines "Digi" with "Bit" to represent the smallest fraction of DigiByte.
> * Digi: Keeping it simple, you could refer to the smallest unit of DigiByte simply as "Digi," which is derived from the name of the cryptocurrency itself.
> 
> Maybe something like this:
> 
> * DGB - DigiBytes
> * mDGB - milli-DigiBytes [milliDigi] - 1/1 000
> * µDGB - micro-DigiBytes - [microDigi] - 1/1 000 000
> * Digitoshi - [Digi] - 1/100 000 000
> 
> Just throwing out ideas...

I like the name "DigiBit"... just my two "DigiBits" :)

**Comment by saltedlolly** [comment]
My hesitance with digi is that it is very close to digibyte itself. I have heard people refer to DGB itself as digis.

I'm open to all and any idea though. It's good to have to have the discussion.

**Comment by saltedlolly** [comment]
Some other suggestions from ChatGPT:

When renaming denominations for something like DigiByte to make them distinctive and intuitive, it's beneficial to consider both the scale of the denomination and its ease of use in conversation. Here are some alternative suggestions:

DGB - DigiBytes
- Keep as is for the base unit.

mDGB - milli-DigiBytes (1/1,000 of a DigiByte)
- MiniByte (A simple, catchy name that indicates a smaller unit)

µDGB - micro-DigiBytes (1/1,000,000 of a DigiByte)
- NanoByte (While technically "nano" suggests a billionth, it's often used colloquially to denote something very small, which might make it intuitive for general use)

Digitoshi - (1/100,000,000 of a DigiByte)
- Biti (A fresh and short name that differentiates it from DigiByte while retaining a hint of the original naming scheme. "Biti" could be a playful take on "bit", a fundamental unit of digital information.)
- PicoByte (Incorporating the "pico-" prefix to signify smallness, though it traditionally means one trillionth, it might be easier for users to relate to the concept of very small units)

This approach aims to maintain a clear distinction between each denomination while ensuring the names are engaging and easy to remember.

**Comment by saltedlolly** [comment]
I've been pondering this since yesterday, and I think out of the suggestions so far, I also prefer the term **digibit(s)** for the DigiByte equivalent of a Satoshi. Colloquially known as **bit(s)** for short. I think it would be good to make it lowercase to make it more distinct from 'DigiByte']

I'm thinking:

- mDGB - milli-DigiBytes [milliDGB] - 1/1 000
- µDGB - micro-DigiBytes - [microDGB] - 1/1 000 000
- digibit - digibits - [digibit]- 1/100 000 000

Has anybody got strong objections to that as a name? Any better suggestions?

**Comment by beggsdl** [comment]
That looks good to me.

**Comment by saltedlolly** [comment]
@gto90 @JaredTate @ycagel @Jongjan88 @j50ng Any objections to the above? Or better suggestions?

**Comment by JaredTate** [comment]
> I've been pondering this since yesterday, and I think out of the suggestions so far, I also prefer the term **digibit(s)** for the DigiByte equivalent of a Satoshi. Colloquially known as **bit(s)** for short. I think it would be good to make it lowercase to make it more distinct from 'DigiByte']
> 
> I'm thinking:
> 
> * mDGB - milli-DigiBytes [milliDGB] - 1/1 000
> * µDGB - micro-DigiBytes - [microDGB] - 1/1 000 000
> * digibit - digibits - [digibit]- 1/100 000 000
> 
> Has anybody got strong objections to that as a name? Any better suggestions?

That sounds fine to me.

**Comment by saltedlolly** [comment]
I am working on a PR to make these changes and have been working my way though the codebase changing all mentions of satoshi/sats.

It's a small detail, but I am also realising that it might be better if the abbrreviated version of 'digibit' is 'dbit' rather than just 'bit'. Otherwise we have situations where it says 'x bit/byte' (i.e. x digibit/byte). That could be very confusing as one is data and the other is money. I think 'dbit/byte' is a bit clearer.

**Comment by saltedlolly** [comment]
I have updated the wiki to reflect this: https://dgbwiki.com/index.php?title=DigiByte#Subunits

(Update: the change has been reverted while this is still under discussion.)

**Comment by beggsdl** [comment]
> I am working on a PR to make these changes and have been working my way though the codebase changing all mentions of satoshi/sats.
> 
> It's a small detail, but I am also realising that it might be better if the abbrreviated version of 'digibit' is 'dbit' rather than just 'bit'. Otherwise we have situations where it says 'x bit/byte' (i.e. x digibit/byte). That could be very confusing as one is data and the other is money. I think 'dbit/byte' is a bit clearer.

I was thinking along the same lines when I was looking at this and thinking about it last night. I like it.

**Comment by Neversate** [comment]
Me brother had a humorous idea. Call them yoshis instead of dbits

**Comment by saltedlolly** [comment]
I did some digging:

- Litecoin call it a "litoshi"
- Bitcoin Cash call it a "satoshi"
- Dogecoin does not have a name. It is apparently just 0.00000001 DOGE.
- Dash also does not have a name. It is apparently just 0.00000001 DASH.
- Zcash call it a "zatoshi"
- Decred call it a "satoshi"
- Cardana calls it a "lovelace" (This naming convention honors Ada Lovelace, who is often celebrated as the first computer programmer due to her work on Charles Babbage's early mechanical general-purpose computer, the Analytical Engine.)
- Komodo call it a "satoshi"

Other coins that I found (Ravencoin, Vertcoin etc.) seem to mostly not have a term meaning they likely just stick with 'satoshi' or just don't call it anything.

**Comment by saltedlolly** [comment]
A possible compromise which might be more universally accepted by the community could be to call it a **digisat (dsat)**. This would maintain a connection to the term Satoshi, while being distinct to DigiByte. It's also a lot less of a mouthful, DigiSatoshi.

Thoughts?

**Comment by saltedlolly** [comment]
I have reverted the dgbwiki to its original names as they were two days ago as this is still under discussion: https://dgbwiki.com/index.php?title=DigiByte#Subunits

**Comment by mraksoll4** [comment]
Dbit
Digit

**Comment by JaredTate** [comment]
Going to close this since we just merged https://github.com/DigiByte-Core/digibyte/pull/229. If anyone has any other issues with it feel free to re-open this issue.
