### ISSUE TITLE
CANNOT SEND DIGIBYTE FROM APPLICATION 

### ISSUE THREAD

**Issue by Erinsandaker** [DigiByte-Core/digibyte#200]
<!I have been trying for over a year to access my DigiByte wallet app. It will try and sync for days and never finished. I would like to send my DigiByte but it won’t allow that either. Can someone please direct me to a person for help?? Not a forum, not a deadend website either.

 General digibyte questions and/or support requests are best directed to the DigiByte StackExchange at https://digibyte.stackexchange.com - IS NOT A THING!! Another DEAD-END

-- This issue tracker is only for technical issues related to DigiByte Core.

General digibyte questions and/or support requests are best directed to the DigiByte StackExchange at https://digibyte.stackexchange.com.

For reporting security issues, please read instructions at https://digibyte.org/en/contact/.

If the node is "stuck" during sync or giving "block checksum mismatch" errors, please ensure your hardware is stable by running memtest and observe CPU temperature with a load-test tool such as linpack before creating an issue!

Any report, issue or feature request related to the GUI should be reported at
https://github.com/digibyte-core/gui/issues/
-->

**Comment by JaredTate** [comment]
Can you please be more specific? Which application, what version? Do you have screenshots or log information? Without more details, it's impossible to help. Cheers

**Comment by Erinsandaker** [comment]
Hi Jared,

Thank you for responding so quickly! I am not sure what version the app is - maybe 2.0.1? I get to the screen where I add my other wallet address where I am sending my coin to and put in my passcode, then the application closes after I submit or just makes me put in the passcode over and over.

As for syncing, I've attached a screen shot - it just says connecting and can run like this for days...

Thank you,


Erin Sandaker, CRSP



________________________________

**Comment by JaredTate** [comment]
> Hi Jared, Thank you for responding so quickly! I am not sure what version the app is - maybe 2.0.1? I get to the screen where I add my other wallet address where I am sending my coin to and put in my passcode, then the application closes after I submit or just makes me put in the passcode over and over. As for syncing, I've attached a screen shot - it just says connecting and can run like this for days... Thank you, Erin Sandaker, CRSP 403-598-0397
> 


Thanks for giving more information, is this a desktop wallet? Or is this a mobile wallet? Also, there no screen shot that was attached to your comment. 

If you're running version 2 of the desktop wallet that's 10 years old and there will be nodes to connect to so you just need to upgrade core desktop wallet to version 8.22. If you are talking about a mobile wallet you will need to sweep the private keys and import them to a different wallet.

**Comment by Erinsandaker** [comment]
Hi Jared,

This is on my phone. Tried to attach the pictures again...

Thank you,


Erin Sandaker, CRSP


________________________________

**Comment by Sbosvk** [comment]
Unfortunately the image didn't make it through this time either. Are you referring to the DigiByte Mobile app? What is the app icon, if you could explain? Android or iOS?

**Comment by JaredTate** [comment]
> Hi Jared, This is on my phone. Tried to attach the pictures again... Thank you, Erin Sandaker, CRSP 

Ok, so if it is a mobile wallet you will need to sweep the wallet and import keys to a different wallet. As the older ones are not actively supported at this time. Your DGB is still there and retrievable though.

On a side note, all of this conversation is publicly displayed on Github and this is the repository for the core desktop wallet and main protocol. So not really the place for mobile wallet support, but I understand you want help.

I would recommend removing your phone # from comments as that's easy to get scraped and get targeted on here by bad actors.

**Comment by JaredTate** [comment]
> Unfortunately the image didn't make it through this time either. Are you referring to the DigiByte Mobile app? What is the app icon, if you could explain? Android or iOS?

But yes, there are a ton of mobile apps this could be that support DGB, so knowing the exact app your using is needed. Cheers

**Comment by Erinsandaker** [comment]
Hi Jared,

Strange, they seem to be sending. This is the Digibyte Mobile app and is iOS.



Thank you,


Erin Sandaker, CRSP



________________________________

**Comment by Erinsandaker** [comment]
[cid:b2fce827-7e1a-49a0-ad6d-d955503c0baf]
Thank you,


Erin Sandaker, CRSP


________________________________

**Comment by JaredTate** [comment]
> Hi Jared, Strange, they seem to be sending. This is the Digibyte Mobile app and is iOS. Thank you, Erin Sandaker, CRSP

It appears you are responding directly in an email chain so they will not appear here for us. We are replying to you directly on the GitHub website, so they will not show for us. I removed your phone # from the above comments so it doesn't get scraped and targeted.

As for the iOS DGB wallet, you will need to scrape your private keys from the wallet and move your DGB to a new wallet.

**Comment by Erinsandaker** [comment]
[cid:971abaf9-8f1d-4659-ab7b-0dd28078544e]

Maybe you can see this icon? It is the actual Digibyte App

Thank you,


Erin Sandaker, CRSP


________________________________

**Comment by Sbosvk** [comment]
If you have a Telegram or Discord account I suggest we move this discussion there where we could provide assistance and/or guidance a bit easier. As Jared says this repository that this conversation is now being held under is for the DigiByte Core application for desktop computers, it would be better to move the conversation elsewhere where it is more relevant.
If you have an account for the aforementioned platforms you can join our discussion groups/channels on the following links respectively:
https://t.me/DigiByteCoin
https://dsc.gg/DigiByteDiscord

Please be aware of scammers that may try to trick you, never respond to private/direct messages trying to provide you support.

**Comment by Erinsandaker** [comment]
Thank you. I keep trying to move my DGB but the application keeps shutting down before I can get them out. Then I re-open the application and try again. Is there another way possibly? Through a computer rather than the mobile phone? I downloaded Digibyte Core Wallet to my computer and there doesn't seem to be a login or sign in button for me to actually get to my stuff.

Thank you,


Erin Sandaker, CRSP



________________________________

**Comment by JaredTate** [comment]
> If you have a Telegram or Discord account I suggest we move this discussion there where we could provide assistance and/or guidance a bit easier. As Jared says this repository that this conversation is now being held under is for the DigiByte Core application for desktop computers, it would be better to move the conversation elsewhere where it is more relevant. If you have an account for the aforementioned platforms you can join our discussion groups/channels on the following links respectively: https://t.me/DigiByteCoin https://dsc.gg/DigiByteDiscord
> 
> Please be aware of scammers that may try to trick you, never respond to private/direct messages trying to provide you support.

As @Sbosvk suggested I would head to the DGB telegram or Discord to find some great folks who can help you get this issue resolved better than right here.

FYI this conversation is logged publicly at this link on GitHub website, so its not a good idea to keep sharing personal information about you or your crypto here:

https://github.com/DigiByte-Core/digibyte/issues/200

**Comment by Erinsandaker** [comment]
Hi Jared,

I was able to get signed up for discord but am not sure how to access our conversation. My ussername is erin02181. Can you try to message me on there

Thank you,


Erin Sandaker


________________________________

**Comment by JaredTate** [comment]
> Hi Jared, I was able to get signed up for discord but am not sure how to access our conversation. My ussername is erin02181. Can you try to message me on there Thank you, Erin Sandaker
> […](#)

Erin,

Inside the DigiByte discord there is a "tech-support" channel. If you drop a comment that you would like help sweeping your iOS wallet to move your stuck DGB out of your wallet several people can help. 

One such tool you can use is found here: https://digisweep.digiassetx.com/

You will need to identify your wallet backup phrase key words and you will need to setup a new wallet to send your DGB to. This wallet can be any new wallet you choose. There are a lot of options.

You can find more wallet options here:
https://www.digibyte.org/en-us/#downloads

**Comment by JaredTate** [comment]
> erin02181

Erin,
We messaged you in the tech support chat on discord, it appears you need to verify your account first with discord before you can see the DigiByte chats.

Cheers

**Comment by Sbosvk** [comment]
Hi, Erin.
We have manually verified your account so you should now be able to see the chat @JaredTate is referring to. 🙃

**Comment by ycagel** [comment]
Has this been resolved?

**Comment by Sbosvk** [comment]
@ycagel This has not been resolved yet, communication stopped abruptly. They did make it into Discord so now we are just waiting to hear from them again. But in my opinion we can get rid of this issue.

**Comment by Erinsandaker** [comment]
Thank you very much for all of your help. Communication stopped because I don’t have time to finish working on this today. Can I please still contact you Monday if I don’t figure it out?

Thank you,

Erin Sandaker, CRSP
________________
