### ISSUE TITLE
Transaction did not send

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/digibyte#225]
**Expected behavior**
First transaction: Attempted to send 90 DGB from Core wallet to mobile wallet.  
Second transaction: Attempted to send one transaction to seven different addresses. 

**Actual behavior**
First transaction did not send, screen display has a question mark to the left of date/time/label/amount.
Second transaction did not send, screen display has a question marks to the left of date/time/label/amount.
  

**To reproduce**
During the first transaction, I accidentally closed the wallet after signing transaction.
As for the second transaction, I selected seven different addresses sign transaction and resulted in the above mentioned behavior.
 

**System information**
I have DigiByte Core 8.22.0 rc-4 installed on Windows pc desktop. Local disk space is 237 GB with72.1 GB free. 
Yesterday I was attempting to send 90 DGB from Core wallet to mobile wallet, after I signed the transaction, I accidently closed the Core wallet instead of minimizing the window. I started the wallet over; the transaction did not go through and there was a question mark where it shows status of the transaction. 
I was able to send two transactions after that, however the following transaction did not process, the transaction itself was to seven different addresses. I will attach two screenshots with details of the transactions. I can see the coins on the explorer just not in my wallet.
I assumed the first failed transaction was due to user error, however, due to the second failed transaction, now I think it might be a bug. I uninstalled/reinstalled and the core wallet still showing same balance. I assume in cases like these where a transaction fails and the coins did not move, that the wallet would update the correct balance. I messaged @ycagel and he said to write it up as an issue.

1st tx
![1](https://github.com/DigiByte-Core/digibyte/assets/136190014/62341b69-2abf-457a-ae42-c131228bcef0)
2nd tx
![2](https://github.com/DigiByte-Core/digibyte/assets/136190014/e96cf165-0b62-420e-a52a-74bbbf63531e)
 
Address: dgb1q470nypn3xuk2p8luk8vs2nf7xnqm4havh2eh6x
Ballance: 1835.5487

**Comment by ghost** [comment]
Testnet / Mainnet?
Legacy wallet / Descriptor wallet?

**Comment by JaredTate** [comment]
It's stuck in mempool, which happens in situations like that. Go to Window-> Console->

Run command: 
```
abandontransaction "txid"
```
Replace "txid" with the actual transaction ID between quotes.  It will auto-clear after a couple days as well.

Example:
```
abandontransaction "1075db55d416d3ca199f55b6084e2115b9345e16c5cf302fc80e9d5fbf5d48d"
```

Edit: In your transaction history I actually think you can right click on it and click "abandon" as well.

**Comment by DGBNOOB** [comment]
Thank you Jared,
I tried the command line on the first transaction and I'll wait for it to abandon the tx. 
I tried right click on second transaction and it worked instantly funds are available. 
closing issue.

**Comment by beggsdl** [comment]
@DGBNOOB 
Do you have a message like this in debug.log at the time you created that transaction that did not send?
"CommitTransaction(): Transaction cannot be broadcast immediately, too-long-mempool-chain, exceeds descendant size limit for tx 268820d9f5dc9729ed0e2c96a8da6ae877427b000b3090ba1c17c95e7bebc9a3 [limit: 101000]"

**Comment by DGBNOOB** [comment]
> Testnet / Mainnet? Legacy wallet / Descriptor wallet?

@Jongjan88 
Mainnet but not sure about Legacy/Descriptor

**Comment by DGBNOOB** [comment]
> @DGBNOOB Do you have a message like this in debug.log at the time you created that transaction that did not send? "CommitTransaction(): Transaction cannot be broadcast immediately, too-long-mempool-chain, exceeds descendant size limit for tx 268820d9f5dc9729ed0e2c96a8da6ae877427b000b3090ba1c17c95e7bebc9a3 [limit: 101000]"

I did not check. I just tried opening the debug log file and i got a message "logfile to large for note pad" "use another editor to edit the file"

**Comment by beggsdl** [comment]
> > @DGBNOOB Do you have a message like this in debug.log at the time you created that transaction that did not send? "CommitTransaction(): Transaction cannot be broadcast immediately, too-long-mempool-chain, exceeds descendant size limit for tx 268820d9f5dc9729ed0e2c96a8da6ae877427b000b3090ba1c17c95e7bebc9a3 [limit: 101000]"
> 
> I did not check. I just tried opening the debug log file and i got a message "logfile to large for note pad" "use another editor to edit the file"

You could open it in WordPad.

**Comment by DGBNOOB** [comment]
I keep getting the same message.


![notepad (002)](https://github.com/DigiByte-Core/digibyte/assets/136190014/088a1122-54c9-40f4-93a8-02c60ea60d29)

**Comment by DGBNOOB** [comment]
I did receive this message in console:
abandontransaction "00e154cf1cfd7ae796bb3b62f8f2f5377256a552d9678b4d56fbafd60855389d 
Transaction not eligible for abandonment (Code 5)

**Comment by ycagel** [comment]
> > @DGBNOOB Do you have a message like this in debug.log at the time you created that transaction that did not send? "CommitTransaction(): Transaction cannot be broadcast immediately, too-long-mempool-chain, exceeds descendant size limit for tx 268820d9f5dc9729ed0e2c96a8da6ae877427b000b3090ba1c17c95e7bebc9a3 [limit: 101000]"
> 
> Did you find a fix for this problem @beggsdl ?
> 
> I am facing the same issue with Digibyte transactions, glad to know I am not alone. I accidentally upgraded my production Digibyte to the latest version (I honestly didn't know I wasn't supposed to), and since then, I haven't been able to use Digibyte without issues. I can't roll back also, I have tried plenty of times, but it fails. I had to put DGB on maintenance on my project because of this.
> 
> Every one in three transactions fails with this message. I have to run abandontransaction every time, and if I don't, it eventually gets processed after one or two weeks.

Can you provide more information on this? 

What version are you running?
How much was the transaction?
How much was the fee?
What was the transaction doing?
How was it sent?

This error does not seem to be for a normal transaction.

**Comment by junytuny** [comment]
@ycagel You can see #234 with all the details of this issue.
