### ISSUE TITLE
Public Electrum Server?

### ISSUE THREAD

**Issue by JohnnyLawDGB** [DigiByte-Core/digibyte#240]
I know Komodo maintains one for their wallet integration, do we know of any other public servers?  From what I can see, it wouldn't be too difficult to set one up.

**Comment by JohnnyLawDGB** [comment]
For context, looking to be able to complete PR for addition to Cake Wallet.

**Comment by LeroyGerrits** [comment]
Would love to know this as well. Many public libraries and repos that have interfaces for altcoin implementation seem to rely on Electrum servers. I haven't seen a public one for DigiByte yet.

**Comment by ycagel** [comment]
I think it was done years ago. Not sure if this is of any help as a starting point.

https://github.com/dgbholdings/electrum-dgb

**Comment by saltedlolly** [comment]
There are some old repos relating to this in DigiByte Core but they are deprecated: https://github.com/DigiByte-Core?q=electrum&type=all&language=&sort=

It looks it would require forking the latest Electrum repos for Bitcoin and going from there.

**Comment by ycagel** [comment]
That would be the way to do it.

**Comment by cipig** [comment]
the latest electrumx server code is here: https://github.com/spesmilo/electrumx
it supports DGB, so no need for any changes, just install and run
