### ISSUE TITLE
RC4 Announcement Discussion

### ISSUE THREAD

**Issue by jason-at-github** [DigiByte-Core/digibyte#241]
With us being in the testing phase for RC4, I'm reaching out to propose the establishment of an announcement discussion dedicated to this stage of development. Drawing from the success of past RC* discussions, having a centralized space where the community, including miners, node operators, and end users, can come together to share their results and collaborate with the team would immensely enhance our testing efforts. This initiative not only fosters transparency but also strengthens community engagement, vital for the continued growth of DigiByte. Your support in creating this platform would be greatly appreciated as we strive to ensure the success of RC4.

**Comment by JaredTate** [comment]
Here is a new discussion thread, thanks for pointing this out and starting the discussion: https://github.com/orgs/DigiByte-Core/discussions/242
