### ISSUE TITLE
5 Year no Update to Core. Why?

### ISSUE THREAD

**Issue by idanzam** [DigiByte-Core/digibyte#249]
the last time the core was updated was 5 years ago?

that mean no Devop and no Roadmap.

Is this coin going on path RIP ?

**Comment by nadav32p** [comment]
The newest core protocol v8.22.0 has been in the works for a few years.
From my understanding It is the largest most complex upgrade digibyte has
had in its existence. It's in its final stages. You can see where they are
at. https://github.com/digibyte-core

**Comment by Sbosvk** [comment]
"Final stages" for over two years.

**Comment by idanzam** [comment]
Mmm ok.
Plesee make also docker img for pool owners.

Ty

בתאריך יום א׳, 13 באוק׳ 2024, 22:31, מאת Oliver Krilov ‏<
***@***.***>:
