### ISSUE TITLE
Multi-algo not working with cpuminer

### ISSUE THREAD

**Issue by Jolly-Pirate** [DigiByte-Core/digibyte#52]
Running digibyte in regtest mode (`digibyted -regtest`) on two nodes connected to each other, I mined the first 150 blocks with `digibyte-cli -regtest generatetoaddress`, everything goes fine, the multi-algos are active as well as the softforks:
```
{
  "chain": "regtest",
  "blocks": 159,
  "headers": 159,
  "bestblockhash": "32e2dfdb9c068e4a93afd92999fcd772f9c12b441cf69319f1221bb5745e190e",
  "mediantime": 1622079644,
  "verificationprogress": 1,
  "initialblockdownload": false,
  "chainwork": "00000000000000000000000000000000000000000000000000000000e7db92f1",
  "size_on_disk": 48177,
  "pruned": false,
  "difficulties": {
    "sha256d": 4.656542373906925e-10,
    "scrypt": 4.583655290791708e-05,
    "groestl": 4.656542373906925e-10,
    "skein": 4.656542373906925e-10,
    "qubit": 4.656542373906925e-10
  },
  "softforks": [
  ],
  "bip9_softforks": {
    "csv": {
      "status": "defined",
      "startTime": 0,
      "timeout": 9223372036854775807,
      "since": 0
    },
    "segwit": {
      "status": "active",
      "startTime": -1,
      "timeout": 9223372036854775807,
      "since": 0
    },
    "nversionbips": {
      "status": "defined",
      "startTime": 9,
      "timeout": 7308892999128540205,
      "since": 0
    },
    "reservealgo": {
      "status": "active",
      "startTime": -1,
      "timeout": 9223372036854775807,
      "since": 0
    },
    "odo": {
      "status": "active",
      "startTime": -1,
      "timeout": 94171832018720,
      "since": 0
    }
  },
  "warnings": ""
}
```
However, when I try to solo mine locally with cpuminer (https://github.com/tpruvot/cpuminer-multi), only the scrypt algo works, while the other four (sha256d, groestl, skein, qubit) don't work at all. Their PoW are rejected by the daemon with the following error:
`ERROR: ProcessNewBlock: AcceptBlock FAILED (high-hash, proof of work failed (code 16))`

Am I missing something? Is there a special cpuminer version that works with Digibyte?

**Comment by ghost** [comment]
You have to set algo=sha256 in digibyte.conf. You can use https://github.com/Jongjan88/dgbminer

**Comment by ghost** [comment]
We can close this PR @ycagel

**Comment by ycagel** [comment]
Appreciate all the work @Jongjan88!
