### ISSUE TITLE
help bootstrapping a DigiByte Core version v6.14.2.0-4fbe88b-DGB (64-bit) running on windows 10 64bit

### ISSUE THREAD

**Issue by jaydeeatechs** [DigiByte-Core/digibyte#60]
help bootstrapping DigiByte Core version v6.14.2.0-4fbe88b-DGB (64-bit)

 i backed up my wallet.dat file, deleted all files except it, and ran the zip file (described in the dgbwiki article) into the digibyte wallet folder.   The process did work and the wallet launched.

 wallet says connecting to peers - 7 years and 27 weeks behind  (however even running overnight nothing changes in terms of status)

  see above

 DigiByte Core version v6.14.2.0-4fbe88b-DGB (64-bit)

  Windows 10 - 64bit  (ssd hard drive)

 I originally loaded dbg on my wallet back in 2017 and it sync'd for a long time, but eventually stopped syncing and hasn't for years.   I'm trying to resolve this so i can move the tokens to a trezor (which wasn't supporting dbg at the time).

 not sure  if this is what you need but the debug log file has this when I opened it:  2021-07-18 16:17:46 
[debug.log](https://github.com/DigiByte-Core/digibyte/files/6872463/debug.log)

**Comment by mctrivia** [comment]
6.14.2 is older then the last fork and there for can not be used any more.  Please upgrade to at least 7.17.2

**Comment by jaydeeatechs** [comment]
Thanks.  
- Do I (save my wallet.dat file) uninstall the old version entirely, then download and install 7.17.2?  And if so, how to a get the newer version pointed to my wallet?
- Or do i leave the old wallet alone and just install the new version?
-  is there a newer version than 7.17.2 I should opt for instead?  Which version is more likely to work on such an old wallet?

...basically any input on how NOT to lose all my coins?

**Comment by mctrivia** [comment]
newest version is 7.17.3 and you should use it.  7.17.2 is oldest useable version.

For safety make sure you have a backup of wallet.dat(you should always keep safe backup) then just install the new version.
If you have run the old version after July 2019(which you have) delete the blocks and indexes folders(indexes does not always exist) before running the new one.

**Comment by jaydeeatechs** [comment]
Many thanks.  Last question:  do i 1) delete the blocks and indexes,  then 2) uninstall the old version,  then 3) install the new version?     or rather  #1 & #3   (i.e., will the new version install cleanly over the old version)?

**Comment by mctrivia** [comment]
no need to uninstall old version.  installing new version will overwrite it.  Order does not matter as long as you delete the folders when the wallet is not running

**Comment by ycagel** [comment]
Has this been resolved?

**Comment by jaydeeatechs** [comment]
Yes all good thanks!

Sent via mobile
