### ISSUE TITLE
Digibyte SHA256 is not minting anymore :(

### ISSUE THREAD

**Issue by lurchinms** [DigiByte-Core/digibyte#71]
I have not been able to mint a coin since: 
Wed Sep 15 2021 06:41:29 GMT-0500 (Central Daylight Time)
After block height  13656975

I also noticed that the Coin Difficulty has been much lower that the past.

What is going on with it?

**Comment by lurchinms** [comment]
I have restored my wallet.dat file and also change the mining to address to another one.

**Comment by lurchinms** [comment]
I also down-graded the linux version of the wallet back to v7.17.2

**Comment by gto90** [comment]
Hello,

Extraction on this wallet is indeed showing SHA256 blocks: https://chainz.cryptoid.info/dgb/extraction.dws?21194055.htm

This pool appears to be more dominant in Scrypt and Quibit, but they are still generating SHA256 blocks.  Here are a couple of examples:

https://chainz.cryptoid.info/dgb/block.dws?13703394.htm
https://chainz.cryptoid.info/dgb/block.dws?13703357.htm

You might consider reaching out to the mining community here: https://t.me/dgbmining

If you are able to provide more information we will take a look.
